AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: A Lambda to check isomorphism between two graphs.
Resources:
  function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/sigma-0.0.1-SNAPSHOT.jar
      Handler: net.torrance.gilleain.sigma.IsomorphismHandler
      Runtime: java8
      Description: Java function
      MemorySize: 512
      Timeout: 10
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AWSLambdaVPCAccessExecutionRole
      Tracing: Active
